name = "SSS 1.19.3"
author = "spacky"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d3498af61feec59d3c02feb64fc1f3a84dc25351598ab5d2b1ecf62bfc1953c"

[versions]
minecraft = "1.19.3"
quilt = "0.18.2"
