name = "SSS 1.19.3"
author = "spacky"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d65e1bcb01f52a2810d0b15931cd317c5d56e18f6c22a707aced26b1eee3680"

[versions]
minecraft = "1.19.3"
quilt = "0.17.11"
