name = "SSS 1.19.3"
author = "spacky"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a2d7c319f28359a2091714fed221d0f65aa7c3fa0ccdc55dd3f5179a38768fb"

[versions]
minecraft = "1.19.3"
quilt = "0.17.11"
