name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3c8d121ecd47b0e42d944d12da96bb183bf44ed76c2a216a42a4a41cc2034c2"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"
