name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.3.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7842f4a0a9a195b0be7088760fcf1b5a73c6bce8678de0896e35a1d0ad89991"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
datapack-folder = "global_packs/required_data"
