name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a76b31e93e7ced3ba11fc29f1b61e4a8e6c4cf34df002873d7313a3178cb609b"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
datapack-folder = "global_packs/required_data"
