name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54fa14b81c3721d315ffb117522e495cb330e3b31ed0e3816e2c2679e1fc7b61"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
datapack-folder = "global_packs/required_data"
