name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.3.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9baffb70a75c2763be134ffd9fb2e9c01f42af5fba10d28123a0d40663e2f180"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
datapack-folder = "global_packs/required_data"
