name = "SSS 1.20.1 Create"
author = "spacky"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c85bf13803ec4f0fd4fbf362d82523ab1fb3e548034d5a06b8d87d1a2c8752ce"

[versions]
minecraft = "1.20.1"
quilt = "0.21.0"

[options]
datapack-folder = "global_packs/required_data"
